// example/src/pages/index/index.tsx
import { View, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import React, {Suspense} from "react";
import './index.less'

const AsyncComponentFirst = React.lazy(async () => {
  const result = await import('@/components/async-component-first')
  return {default: result.AsyncComponentFirst}
})

const AsyncComponentSecond = React.lazy(async () => {
  const result = await import('@/components/async-component-second')
  return {default: result.AsyncComponentSecond}
})



export default function Index () {
  useLoad(() => {
    console.log('Page loaded.')
  })

  return (
    <View className='index'>
      <Suspense fallback={<View>Loading...</View>}>
        <AsyncComponentFirst />
        <AsyncComponentSecond />
      </Suspense>
      <Text>Hello world!</Text>
    </View>
  )
}

// example/framework-vue/src/pages/index/index.vue
<template>
  <view class="index">
    <Suspense>
      <template #default>
        <view>
          <AsyncComponentFirst/>
          <AsyncComponentSecond/>
        </view>
      </template>
      <template #fallback>
        <view>loading...</view>
      </template>
    </Suspense>
    <text>{{ msg }}</text>
  </view>
</template>

<script setup>
import {defineAsyncComponent, ref} from 'vue'
import './index.less'

const AsyncComponentFirst = defineAsyncComponent(async () => {
  return  import('@/components/async-component-first')
  }
)

const AsyncComponentSecond = defineAsyncComponent(() =>
  import('@/components/async-component-second')
)

const msg = ref('Hello world')

</script>
